name: Dependency Submission

on:
  push:
    branches: [ 'main' ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
          cache: gradle
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4